version: "3"
networks:
  loki:
services:
  loki:
    image: grafana/loki:2.6.1
    volumes:
      - /home/rixon/grafana-loki/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki
  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      - /var/log:/var/log
      - /mnt/d/app_logs:/app_logs
      - /home/rixon/grafana-loki/promtail:/etc/promtail
    ports:
      - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
    - /home/rixon/grafana-loki/grafana:/var/lib/grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - loki
